Update draw.io to the latest version
xwikisas/application-diagram pull request #177
Opened 2021-03-17 16:38 UTC by oanalavinia

* upgrade dependency
* we don't need to change the '.min' extension manually since the new webjar contains also the map for the minified files, so the unminifying process is done automatically by the browser
* fix the start step by disabling the checkDrafts option, since a pop-up appeared for opening the file in a new window
* rough library is needed for some shapes from the sidebar
* loadUrl was moved from EditorUi; changed it to make import from URL to work
* hideFooter was removed from the code base
* toggleCompactMode parameter was changed from _forceHide_ to _visible_

2021-03-26 07:20 UTC, oanalavinia commented
Note that after more testing I found another issue while exporting as PDF from XWiki, where any text element is moved from it's place (when exporting using svg).
A commit will be added for this as well

2021-03-31 10:25 UTC, mflorea requested changes
Just 2 minor comments. Looks good otherwise.

2021-03-31 10:25 UTC, mflorea commented on application-diagram-ui/src/main/resources/Diagram/DiagramEditSheet.xml
> +        group.setAttribute('transform', transform);
Would be nice to fix the alignment.

2021-03-31 10:25 UTC, mflorea commented on application-diagram-ui/src/main/resources/Diagram/DiagramEditSheet.xml
> +  // Don't add warning when the viewer doesn't supports SVG 1.1, since we create a fallback for foreignObjects.
```suggestion
  // Don't add warning when the viewer doesn't support SVG 1.1, since we create a fallback for foreignObjects.
```

2021-03-31 12:05 UTC, mflorea approved these changes

2021-03-31 12:08 UTC, merged