Cannot modify diagram title in diagram editor #219
xwikisas/application-diagram pull request #221
Opened 2022-01-27 11:25 UTC by trrenty

2022-01-28 14:52 UTC, mflorea commented
Please upload a screenshot. Thanks.

2022-01-31 14:07 UTC, trrenty commented
@mflorea 
![image](https://user-images.githubusercontent.com/45433221/151808070-2b494300-df3d-4168-9887-628d3ec9c747.png)

2022-02-01 07:52 UTC, mflorea commented
I'm not sure the icon before the "Title" label brings any value, on the contrary, it could be misleading / confusing. Plus it's not consistent (we don't use that icon elsewhere in XWiki before the title label). I think you should drop it. Otherwise it looks OK. Ideally, I would have liked the page title (heading) to be replaced by an "invisible" text input, similar to the in-place edit, in order to avoid the duplication (e.g. "DiagramTest" is displayed twice). But your solution works fine.

2022-02-07 09:21 UTC, mflorea requested changes

2022-02-07 09:21 UTC, mflorea commented on application-diagram-ui/src/main/resources/Diagram/DiagramEditSheet.xml
> +    &lt;div class="col-xs-12 col-md-12"&gt;
I think the ``col-md-`` makes sense only if it has a different value than ``col-xs-``. Basically, the larger screens use by default the same styles as the smaller screens.

2022-02-07 09:21 UTC, mflorea commented on application-diagram-ui/src/main/resources/Diagram/DiagramEditSheet.xml
> +          &lt;label for="xwikiDocTitleInput"&gt;
I know you tried to follow the best practice by applying camel-case but I think it's better in this case to use the same id as in standard wiki edit mode. I know that id is awful but I think consistency is more important in this case.

2022-02-07 09:21 UTC, mflorea commented on application-diagram-ui/src/main/resources/Diagram/DiagramEditSheet.xml
> +            $services.localization.render('core.editors.content.titleField.label')
```suggestion
            $escapetool.xml($services.localization.render('core.editors.content.titleField.label'))
```

Always escape content that you don't control directly. In this case, the translation message can easily break the HTML.

2022-02-07 09:21 UTC, mflorea commented on application-diagram-ui/src/main/resources/Diagram/DiagramEditSheet.xml
> +          &lt;input id="xwikiDocTitleInput" type="text" name="title" value="$escapetool.xml($doc.title)"&gt;
I know it doesn't make much sense to translate structured pages, such as diagram pages, but it is possible. Sure, all translations will share the same diagram object but they can have different titles, so it's best to edit the title corresponding to the current translation:

```suggestion
          &lt;input id="xwikiDocTitleInput" type="text" name="title" value="$escapetool.xml($tdoc.title)"&gt;
```

``tdoc`` stands for "translated" document.

2022-02-24 15:36 UTC, merged