* Diagram saves only the current page in attachments when multiple pages are used
xwikisas/application-diagram pull request #327
Opened 2024-12-09 16:10 UTC by Farcasut

*
Update the code to save all the pages of a diagram, added a new parameter to select witch page you want to see when you use the cache and updated the code to display the cached diagram when exporting a page using the xwiki pdf exporter.

2024-12-16 16:43 UTC, ChiuchiuSorin requested changes
I found the following situation:
- create 3 pages on the diagram macro, add diagrams on each one of them and save
- edit again and delete the second diagram
- now the third diagram is saved as an attachment as diagram2 and diagram3

It seems to me that there is no support for deleting a page. The current implementation correctly overwrites the deleted position, but the remaining attachments are not deleted.
This could also be an issue if a user selects the page index the last created page and then removes it. The expected result would be to have a warning message that there is no such index, or a blank image displayed, but as it is, because the attachment is not removed, it will still display the deleted diagram.

https://github.com/user-attachments/assets/d18e7d9e-8b88-4594-a7e1-f061d5ba1b35

2024-12-16 16:43 UTC, ChiuchiuSorin commented on application-diagram-ui/src/main/resources/Diagram/DiagramEditSheet.xml
> +            pipeDeferred(saveBlobAsImageAttachment(blob, `${getXWikiAttachmentName(index)}.png`, file.documentReference), deferred);
This is over the line limit.

2024-12-16 16:43 UTC, ChiuchiuSorin commented on application-diagram-ui/src/main/resources/Diagram/DiagramMacro.xml
> +          #set ($fileName = "${attachmentName}.svg")
If the selected index does not exist, I'd add a warning similar to the negative page index one.

2025-02-06 08:40 UTC, Farcasut commented
Updated the code to delete all attachments in a single step using a custom REST endpoint, but this causes the save operation to become slower

2025-02-11 13:01 UTC, oanalavinia requested changes
+ some codestyle issues

2025-02-12 08:01 UTC, oanalavinia requested changes

2025-02-12 08:01 UTC, oanalavinia commented on application-diagram-ui/src/main/resources/Diagram/DiagramTranslations.xml
> +rendering.macro.diagram.parameter.pageIndex.description=The index of the page that you want to see when cached is enabled.
WDYT?
```suggestion
rendering.macro.diagram.parameter.pageIndex.description=The index of the page that you want to see when cached is enabled (i.e. use 1 for 1st page of the diagram, 5 for the 5th page)
```

2025-02-12 08:21 UTC, Farcasut commented on application-diagram-ui/src/main/resources/Diagram/DiagramTranslations.xml
> +rendering.macro.diagram.parameter.pageIndex.description=The index of the page that you want to see when cached is enabled.
Yes, the page names start from 1.
![image](https://github.com/user-attachments/assets/da0848b1-480c-444e-8015-0cbc61a06f1c)

2025-02-12 08:27 UTC, Farcasut commented on application-diagram-ui/src/main/resources/Diagram/DiagramMacro.xml
> +        #if ($pageIndex &gt;= 1)
Yes, when I added the new parameter I also attributed a default value

2025-02-12 15:10 UTC, oanalavinia approved these changes
Just one comment, looks good otherwise. Thanks! :)

2025-02-12 15:10 UTC, oanalavinia commented on application-diagram-ui/src/main/resources/Diagram/DiagramTranslations.xml
> +diagram.macro.invalidPageIndex=There is no a diagram page corresponding to this index.
My bad, I forgot an `a` in my suggestion

```suggestion
diagram.macro.invalidPageIndex=There is no diagram page corresponding to this index.
```

2025-02-14 10:57 UTC, merged